// This file is generated by scripts/gen-syscalls.py from include/syscalls.hh.
// To add a new system call, edit syscalls.hh. gen-syscalls.py will be rerun on
// the next build and this file will be modified. Commit in the changed file for
// easier readability.
#define SYS_NR_exit             1
#define SYS_NR_fork             2
#define SYS_NR_read             3
#define SYS_NR_write            4
#define SYS_NR_open             5
#define SYS_NR_close            6
#define SYS_NR_wait             7
#define SYS_NR_execv            11
#define SYS_NR_getpid           20
#define SYS_NR_dup              28
#define SYS_NR_pipe             29
#define SYS_NR_sysinfo          30
#define SYS_NR_sleep            31
#define SYS_NR_plist            32
#define SYS_NR_pinfo            33
#define SYS_NR_pgalloc          34
#define SYS_NR_pgfree           35
#define SYS_NR_gpio             36
#define SYS_NR_detach           37
#define SYS_NR_isopen           38
#define SYS_NR_pipeattch        39
#define SYS_NR_lsdir            40

#define SYSCALL_VECTOR_LEN      40
