name: Run builds and tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install xcompiler
      run: ./scripts/install-ci.sh
    - name: Print xcompiler version
      run: riscv64-linux-gnu-gcc --version
    - name: Run virt tests
      run: make test
    - name: Run u64 dry-run tests
      run: make out/test-output-u64.txt
    - name: Run u32 dry-run tests
      run: make out/test-output-u32.txt
    - name: Run u64 smoke tests
      run: make out/smoke-test-output-u64.txt
    - name: Run u32 smoke tests
      run: make out/smoke-test-output-u32.txt
    - name: Make all binaries
      run: make all
